/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Retweet } from "./Retweet";
import { RetweetCountArgs } from "./RetweetCountArgs";
import { RetweetFindManyArgs } from "./RetweetFindManyArgs";
import { RetweetFindUniqueArgs } from "./RetweetFindUniqueArgs";
import { CreateRetweetArgs } from "./CreateRetweetArgs";
import { UpdateRetweetArgs } from "./UpdateRetweetArgs";
import { DeleteRetweetArgs } from "./DeleteRetweetArgs";
import { Tweet } from "../../tweet/base/Tweet";
import { RetweetService } from "../retweet.service";
@graphql.Resolver(() => Retweet)
export class RetweetResolverBase {
  constructor(protected readonly service: RetweetService) {}

  async _retweetsMeta(
    @graphql.Args() args: RetweetCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Retweet])
  async retweets(
    @graphql.Args() args: RetweetFindManyArgs
  ): Promise<Retweet[]> {
    return this.service.retweets(args);
  }

  @graphql.Query(() => Retweet, { nullable: true })
  async retweet(
    @graphql.Args() args: RetweetFindUniqueArgs
  ): Promise<Retweet | null> {
    const result = await this.service.retweet(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Retweet)
  async createRetweet(
    @graphql.Args() args: CreateRetweetArgs
  ): Promise<Retweet> {
    return await this.service.createRetweet({
      ...args,
      data: {
        ...args.data,

        tweet: args.data.tweet
          ? {
              connect: args.data.tweet,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Retweet)
  async updateRetweet(
    @graphql.Args() args: UpdateRetweetArgs
  ): Promise<Retweet | null> {
    try {
      return await this.service.updateRetweet({
        ...args,
        data: {
          ...args.data,

          tweet: args.data.tweet
            ? {
                connect: args.data.tweet,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Retweet)
  async deleteRetweet(
    @graphql.Args() args: DeleteRetweetArgs
  ): Promise<Retweet | null> {
    try {
      return await this.service.deleteRetweet(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Tweet, {
    nullable: true,
    name: "tweet",
  })
  async getTweet(@graphql.Parent() parent: Retweet): Promise<Tweet | null> {
    const result = await this.service.getTweet(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
